### ISSUE TITLE
Cannot find color scheme 'base16-default'

### ISSUE THREAD

**Issue by BjornMelgaard** [RenatoUtsch/dotnvim#3]
Error detected while processing /home/bjorn/.config/nvim/dotnvim/init.vim:
line  133:
E185: Cannot find color scheme 'base16-default'
Press ENTER or type command to continue

**Comment by BjornMelgaard** [comment]
resolved by 

let g:settings.colorscheme = 'base16-default-dark'

**Comment by RenatoUtsch** [comment]
Yeah, it looks like upstream made this breaking change.

This was solved in the latest version as I throughly refactored the project and moved away from base16 to a true color colorscheme.

**Comment by RenatoUtsch** [comment]
By the way, sorry for not answering this, I don't know why I didn't receive an email about it.
